apiVersion: serverless.minik8s.io/v1alpha1
kind: ServerlessService
metadata:
  name: sentiment-it
  namespace: default
spec:
  image: stevenissleepy/sentiment-it:latest
  port: 8080
  concurrency:
    target: 8
  scale:
    minScale: 0
    maxScale: 4
    idleSeconds: 30
