apiVersion: serverless.minik8s.io/v1alpha1
kind: ServerlessService
metadata:
  name: slow
  namespace: default
spec:
  image: stevenissleepy/slow:latest
  port: 8080
  concurrency:
    target: 1
  scale:
    minScale: 0
    maxScale: 3
    idleSeconds: 30
