apiVersion: serverless.minik8s.io/v1alpha1
kind: ServerlessService
metadata:
  name: classify
  namespace: default
spec:
  image: stevenissleepy/classify:latest
  port: 8080
---
apiVersion: serverless.minik8s.io/v1alpha1
kind: ServerlessService
metadata:
  name: handle-text
  namespace: default
spec:
  image: stevenissleepy/handle-text:latest
  port: 8080
---
apiVersion: serverless.minik8s.io/v1alpha1
kind: ServerlessService
metadata:
  name: handle-image
  namespace: default
spec:
  image: stevenissleepy/handle-image:latest
  port: 8080
---
apiVersion: serverless.minik8s.io/v1alpha1
kind: Workflow
metadata:
  name: media-router
  namespace: default
spec:
  entrypoint: classify
  steps:
    classify:
      function: classify
      branches:
        - when:
            field: route
            equals: image
          next: image
      next: text
    text:
      function: handle-text
    image:
      function: handle-image
